export const countries = [
    { code: 'US', name: 'United States' },
    { code: 'CA', name: 'Canada' },
    { code: 'GB', name: 'United Kingdom' },
    { code: 'AU', name: 'Australia' },
    { code: 'NG', name: 'Nigeria' },
];

export const states: { [countryCode: string]: { code: string, name: string }[] } = {
    US: [
        { code: 'AL', name: 'Alabama' }, { code: 'AK', name: 'Alaska' }, { code: 'AZ', name: 'Arizona' },
        { code: 'AR', name: 'Arkansas' }, { code: 'CA', name: 'California' }, { code: 'CO', name: 'Colorado' },
        { code: 'CT', name: 'Connecticut' }, { code: 'DE', name: 'Delaware' }, { code: 'FL', name: 'Florida' },
        { code: 'GA', name: 'Georgia' }, { code: 'HI', name: 'Hawaii' }, { code: 'ID', name: 'Idaho' },
        { code: 'IL', name: 'Illinois' }, { code: 'IN', name: 'Indiana' }, { code: 'IA', name: 'Iowa' },
        { code: 'KS', name: 'Kansas' }, { code: 'KY', name: 'Kentucky' }, { code: 'LA', name: 'Louisiana' },
        { code: 'ME', name: 'Maine' }, { code: 'MD', name: 'Maryland' }, { code: 'MA', name: 'Massachusetts' },
        { code: 'MI', name: 'Michigan' }, { code: 'MN', name: 'Minnesota' }, { code: 'MS', name: 'Mississippi' },
        { code: 'MO', name: 'Missouri' }, { code: 'MT', name: 'Montana' }, { code: 'NE', name: 'Nebraska' },
        { code: 'NV', name: 'Nevada' }, { code: 'NH', name: 'New Hampshire' }, { code: 'NJ', name: 'New Jersey' },
        { code: 'NM', name: 'New Mexico' }, { code: 'NY', name: 'New York' }, { code: 'NC', name: 'North Carolina' },
        { code: 'ND', name: 'North Dakota' }, { code: 'OH', name: 'Ohio' }, { code: 'OK', name: 'Oklahoma' },
        { code: 'OR', name: 'Oregon' }, { code: 'PA', name: 'Pennsylvania' }, { code: 'RI', name: 'Rhode Island' },
        { code: 'SC', name: 'South Carolina' }, { code: 'SD', name: 'South Dakota' }, { code: 'TN', name: 'Tennessee' },
        { code: 'TX', name: 'Texas' }, { code: 'UT', name: 'Utah' }, { code: 'VT', name: 'Vermont' },
        { code: 'VA', name: 'Virginia' }, { code: 'WA', name: 'Washington' }, { code: 'WV', name: 'West Virginia' },
        { code: 'WI', name: 'Wisconsin' }, { code: 'WY', name: 'Wyoming' }
    ],
    CA: [
        { code: 'AB', name: 'Alberta' }, { code: 'BC', name: 'British Columbia' }, { code: 'MB', name: 'Manitoba' },
        { code: 'NB', name: 'New Brunswick' }, { code: 'NL', name: 'Newfoundland and Labrador' }, { code: 'NS', name: 'Nova Scotia' },
        { code: 'ON', name: 'Ontario' }, { code: 'PE', name: 'Prince Edward Island' }, { code: 'QC', name: 'Quebec' },
        { code: 'SK', name: 'Saskatchewan' }
    ],
    AU: [
        { code: 'ACT', name: 'Australian Capital Territory' }, { code: 'NSW', name: 'New South Wales' }, { code: 'NT', name: 'Northern Territory' },
        { code: 'QLD', name: 'Queensland' }, { code: 'SA', name: 'South Australia' }, { code: 'TAS', name: 'Tasmania' },
        { code: 'VIC', name: 'Victoria' }, { code: 'WA', name: 'Western Australia' }
    ],
    NG: [
        { code: 'AB', name: 'Abia' }, { code: 'AD', name: 'Adamawa' }, { code: 'AK', name: 'Akwa Ibom' },
        { code: 'AN', name: 'Anambra' }, { code: 'BA', name: 'Bauchi' }, { code: 'BY', name: 'Bayelsa' },
        { code: 'BE', name: 'Benue' }, { code: 'BO', name: 'Borno' }, { code: 'CR', name: 'Cross River' },
        { code: 'DE', name: 'Delta' }, { code: 'EB', name: 'Ebonyi' }, { code: 'ED', name: 'Edo' },
        { code: 'EK', name: 'Ekiti' }, { code: 'EN', name: 'Enugu' }, { code: 'FC', name: 'FCT' },
        { code: 'GO', name: 'Gombe' }, { code: 'IM', name: 'Imo' }, { code: 'JI', name: 'Jigawa' },
        { code: 'KD', name: 'Kaduna' }, { code: 'KN', name: 'Kano' }, { code: 'KT', name: 'Katsina' },
        { code: 'KE', name: 'Kebbi' }, { code: 'KO', name: 'Kogi' }, { code: 'KW', name: 'Kwara' },
        { code: 'LA', name: 'Lagos' }, { code: 'NA', name: 'Nasarawa' }, { code: 'NI', name: 'Niger' },
        { code: 'OG', name: 'Ogun' }, { code: 'ON', name: 'Ondo' }, { code: 'OS', name: 'Osun' },
        { code: 'OY', name: 'Oyo' }, { code: 'PL', name: 'Plateau' }, { code: 'RI', name: 'Rivers' },
        { code: 'SO', name: 'Sokoto' }, { code: 'TA', name: 'Taraba' }, { code: 'YO', name: 'Yobe' },
        { code: 'ZA', name: 'Zamfara' }
    ]
};

export const phoneCodes = [
    { code: '+1', name: 'USA/Canada' },
    { code: '+44', name: 'UK' },
    { code: '+61', name: 'Australia' },
    { code: '+234', name: 'Nigeria' },
];

export const allCurrencies = [
  { code: 'USD', name: 'United States Dollar', symbol: '$' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { code: 'GBP', name: 'British Pound Sterling', symbol: '£' },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$' },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$' },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$' },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$' },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
];

export const allLanguages = [
  { code: 'en', name: '🇺🇸 English' },
  { code: 'es', name: '🇪🇸 Español' },
  { code: 'fr', name: '🇫🇷 Français' },
  { code: 'de', name: '🇩🇪 Deutsch' },
  { code: 'it', name: '🇮🇹 Italiano' },
  { code: 'pt', name: '🇵🇹 Português' },
  { code: 'ru', name: '🇷🇺 Русский' },
  { code: 'zh', name: '🇨🇳 中文' },
  { code: 'ja', name: '🇯🇵 日本語' },
  { code: 'ko', name: '🇰🇷 한국어' },
  { code: 'ar', name: '🇦🇪 العربية' },
  { code: 'hi', name: '🇮🇳 हिन्दी' },
];

export const allTimezones = [
    { value: "Etc/GMT+12", label: "(GMT-12:00) International Date Line West" },
    { value: "Pacific/Midway", label: "(GMT-11:00) Midway Island, Samoa" },
    { value: "Pacific/Honolulu", label: "(GMT-10:00) Hawaii" },
    { value: "US/Alaska", label: "(GMT-09:00) Alaska" },
    { value: "America/Los_Angeles", label: "(GMT-08:00) Pacific Time (US & Canada)" },
    { value: "America/Tijuana", label: "(GMT-08:00) Tijuana, Baja California" },
    { value: "US/Arizona", label: "(GMT-07:00) Arizona" },
    { value: "America/Chihuahua", label: "(GMT-07:00) Chihuahua, La Paz, Mazatlan" },
    { value: "US/Mountain", label: "(GMT-07:00) Mountain Time (US & Canada)" },
    { value: "America/Managua", label: "(GMT-06:00) Central America" },
    { value: "US/Central", label: "(GMT-06:00) Central Time (US & Canada)" },
    { value: "America/Mexico_City", label: "(GMT-06:00) Guadalajara, Mexico City, Monterrey" },
    { value: "Canada/Saskatchewan", label: "(GMT-06:00) Saskatchewan" },
    { value: "America/Bogota", label: "(GMT-05:00) Bogota, Lima, Quito, Rio Branco" },
    { value: "US/Eastern", label: "(GMT-05:00) Eastern Time (US & Canada)" },
    { value: "US/East-Indiana", label: "(GMT-05:00) Indiana (East)" },
    { value: "Canada/Atlantic", label: "(GMT-04:00) Atlantic Time (Canada)" },
    { value: "America/Caracas", label: "(GMT-04:00) Caracas, La Paz" },
    { value: "America/Manaus", label: "(GMT-04:00) Manaus" },
    { value: "America/Santiago", label: "(GMT-04:00) Santiago" },
    { value: "Canada/Newfoundland", label: "(GMT-03:30) Newfoundland" },
    { value: "America/Sao_Paulo", label: "(GMT-03:00) Brasilia" },
    { value: "America/Argentina/Buenos_Aires", label: "(GMT-03:00) Buenos Aires, Georgetown" },
    { value: "America/Godthab", label: "(GMT-03:00) Greenland" },
    { value: "America/Montevideo", label: "(GMT-03:00) Montevideo" },
    { value: "America/Noronha", label: "(GMT-02:00) Mid-Atlantic" },
    { value: "Atlantic/Cape_Verde", label: "(GMT-01:00) Cape Verde Is." },
    { value: "Atlantic/Azores", label: "(GMT-01:00) Azores" },
    { value: "Africa/Casablanca", label: "(GMT+00:00) Casablanca, Monrovia, Reykjavik" },
    { value: "Etc/Greenwich", label: "(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London" },
    { value: "Europe/Amsterdam", label: "(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" },
    { value: "Europe/Belgrade", label: "(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague" },
    { value: "Europe/Brussels", label: "(GMT+01:00) Brussels, Copenhagen, Madrid, Paris" },
    { value: "Europe/Sarajevo", label: "(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb" },
    { value: "Africa/Lagos", label: "(GMT+01:00) West Central Africa" },
    { value: "Asia/Amman", label: "(GMT+02:00) Amman" },
    { value: "Europe/Athens", label: "(GMT+02:00) Athens, Bucharest, Istanbul" },
    { value: "Asia/Beirut", label: "(GMT+02:00) Beirut" },
    { value: "Africa/Cairo", label: "(GMT+02:00) Cairo" },
    { value: "Africa/Harare", label: "(GMT+02:00) Harare, Pretoria" },
    { value: "Europe/Helsinki", label: "(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius" },
    { value: "Asia/Jerusalem", label: "(GMT+02:00) Jerusalem" },
    { value: "Europe/Minsk", label: "(GMT+02:00) Minsk" },
    { value: "Africa/Windhoek", label: "(GMT+02:00) Windhoek" },
    { value: "Asia/Kuwait", label: "(GMT+03:00) Kuwait, Riyadh" },
    { value: "Europe/Moscow", label: "(GMT+03:00) Moscow, St. Petersburg, Volgograd" },
    { value: "Africa/Nairobi", label: "(GMT+03:00) Nairobi" },
    { value: "Asia/Tbilisi", label: "(GMT+03:00) Tbilisi" },
    { value: "Asia/Tehran", label: "(GMT+03:30) Tehran" },
    { value: "Asia/Muscat", label: "(GMT+04:00) Abu Dhabi, Muscat" },
    { value: "Asia/Baku", label: "(GMT+04:00) Baku" },
    { value: "Asia/Yerevan", label: "(GMT+04:00) Yerevan" },
    { value: "Asia/Kabul", label: "(GMT+04:30) Kabul" },
    { value: "Asia/Yekaterinburg", label: "(GMT+05:00) Yekaterinburg" },
    { value: "Asia/Karachi", label: "(GMT+05:00) Islamabad, Karachi, Tashkent" },
    { value: "Asia/Calcutta", label: "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi" },
    { value: "Asia/Katmandu", label: "(GMT+05:45) Kathmandu" },
    { value: "Asia/Almaty", label: "(GMT+06:00) Almaty, Novosibirsk" },
    { value: "Asia/Dhaka", label: "(GMT+06:00) Astana, Dhaka" },
    { value: "Asia/Rangoon", label: "(GMT+06:30) Yangon (Rangoon)" },
    { value: "Asia/Bangkok", label: "(GMT+07:00) Bangkok, Hanoi, Jakarta" },
    { value: "Asia/Krasnoyarsk", label: "(GMT+07:00) Krasnoyarsk" },
    { value: "Asia/Hong_Kong", label: "(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi" },
    { value: "Asia/Kuala_Lumpur", label: "(GMT+08:00) Kuala Lumpur, Singapore" },
    { value: "Asia/Irkutsk", label: "(GMT+08:00) Irkutsk, Ulaan Bataar" },
    { value: "Australia/Perth", label: "(GMT+08:00) Perth" },
    { value: "Asia/Taipei", label: "(GMT+08:00) Taipei" },
    { value: "Asia/Tokyo", label: "(GMT+09:00) Osaka, Sapporo, Tokyo" },
    { value: "Asia/Seoul", label: "(GMT+09:00) Seoul" },
    { value: "Asia/Yakutsk", label: "(GMT+09:00) Yakutsk" },
    { value: "Australia/Adelaide", label: "(GMT+09:30) Adelaide" },
    { value: "Australia/Darwin", label: "(GMT+09:30) Darwin" },
    { value: "Australia/Brisbane", label: "(GMT+10:00) Brisbane" },
    { value: "Australia/Canberra", label: "(GMT+10:00) Canberra, Melbourne, Sydney" },
    { value: "Australia/Hobart", label: "(GMT+10:00) Hobart" },
    { value: "Pacific/Guam", label: "(GMT+10:00) Guam, Port Moresby" },
    { value: "Asia/Vladivostok", label: "(GMT+10:00) Vladivostok" },
    { value: "Asia/Magadan", label: "(GMT+11:00) Magadan, Solomon Is., New Caledonia" },
    { value: "Pacific/Auckland", label: "(GMT+12:00) Auckland, Wellington" },
    { value: "Pacific/Fiji", label: "(GMT+12:00) Fiji, Kamchatka, Marshall Is." },
    { value: "Pacific/Tongatapu", label: "(GMT+13:00) Nuku'alofa" }
];