
import React, { useState, useMemo } from 'react';
import { useAppContext } from '../../hooks/useAppContext';
import { SupportTicket } from '../../types';
import Icon from '../icons';

const TenantSupport: React.FC = () => {
    const { supportTickets, currentTenant, submitSupportTicket, replyToSupportTicket } = useAppContext();
    const [isCreateModalOpen, setCreateModalOpen] = useState(false);
    const [selectedTicket, setSelectedTicket] = useState<SupportTicket | null>(null);

    const tenantTickets = useMemo(() => {
        if (!currentTenant) return [];
        return [...supportTickets]
            .filter(t => t.tenantId === currentTenant.id)
            .sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());
    }, [supportTickets, currentTenant]);

    const getStatusBadge = (status: SupportTicket['status']) => {
        const styles = {
            'Open': 'bg-green-500/20 text-green-300',
            'In Progress': 'bg-yellow-500/20 text-yellow-300',
            'Closed': 'bg-slate-500/20 text-slate-300',
        };
        return <span className={`px-2 py-1 text-xs font-semibold rounded-full ${styles[status]}`}>{status}</span>;
    };
    
    const CreateTicketModal: React.FC<{ onClose: () => void }> = ({ onClose }) => {
        const [formState, setFormState] = useState({
            subject: '',
            department: 'Technical' as SupportTicket['department'],
            priority: 'Medium' as SupportTicket['priority'],
            message: ''
        });

        const handleSubmit = (e: React.FormEvent) => {
            e.preventDefault();
            if (formState.subject.trim() && formState.message.trim()) {
                submitSupportTicket({
                    subject: formState.subject,
                    department: formState.department,
                    priority: formState.priority,
                    messages: [{
                        id: '', // Will be generated by context
                        sender: 'TENANT',
                        message: formState.message,
                        timestamp: new Date()
                    }]
                });
                onClose();
            }
        };

        return (
            <div className="fixed inset-0 bg-black bg-opacity-70 z-50 flex justify-center items-center p-4">
                <form onSubmit={handleSubmit} className="bg-slate-800 rounded-lg shadow-xl p-6 w-full max-w-lg border border-slate-700">
                    <h3 className="text-xl font-bold mb-4 text-white">Create New Support Ticket</h3>
                    <div className="space-y-4">
                        <input type="text" placeholder="Subject" value={formState.subject} onChange={e => setFormState({...formState, subject: e.target.value})} className="w-full bg-slate-700 p-2 rounded-md" required />
                        <div className="grid grid-cols-2 gap-4">
                            <select value={formState.department} onChange={e => setFormState({...formState, department: e.target.value as any})} className="w-full bg-slate-700 p-2 rounded-md">
                                <option>Technical</option><option>Billing</option><option>General</option>
                            </select>
                            <select value={formState.priority} onChange={e => setFormState({...formState, priority: e.target.value as any})} className="w-full bg-slate-700 p-2 rounded-md">
                                <option>Low</option><option>Medium</option><option>High</option>
                            </select>
                        </div>
                        <textarea placeholder="Please describe your issue..." value={formState.message} onChange={e => setFormState({...formState, message: e.target.value})} rows={5} className="w-full bg-slate-700 p-2 rounded-md" required />
                    </div>
                    <div className="flex justify-end gap-3 mt-6">
                        <button type="button" onClick={onClose} className="px-4 py-2 rounded-md bg-slate-600 hover:bg-slate-500">Cancel</button>
                        <button type="submit" className="px-4 py-2 rounded-md bg-cyan-600 hover:bg-cyan-500">Submit Ticket</button>
                    </div>
                </form>
            </div>
        );
    };

    const ViewTicketModal: React.FC<{ ticket: SupportTicket, onClose: () => void }> = ({ ticket, onClose }) => {
        const [replyMessage, setReplyMessage] = useState('');

        const handleReply = () => {
            if (replyMessage.trim()) {
                replyToSupportTicket(ticket.id, { sender: 'TENANT', message: replyMessage.trim() });
                // Optimistically update view
                setSelectedTicket(prev => prev ? { ...prev, messages: [...prev.messages, {id: `msg-${Date.now()}`, sender: 'TENANT', message: replyMessage.trim(), timestamp: new Date()}]} : null);
                setReplyMessage('');
            }
        };

        return (
            <div className="fixed inset-0 bg-black bg-opacity-70 z-50 flex justify-center items-center p-4">
                <div className="bg-slate-800 rounded-lg shadow-xl w-full max-w-2xl max-h-[90vh] flex flex-col border border-slate-700">
                    <div className="p-4 border-b border-slate-700">
                        <div className="flex justify-between items-start">
                             <h3 className="text-xl font-bold text-white">{ticket.subject}</h3>
                             <button onClick={onClose} className="text-slate-400 hover:text-white"><Icon name="x-mark" className="w-6 h-6"/></button>
                        </div>
                        <p className="text-sm text-slate-400">Status: {getStatusBadge(ticket.status)}</p>
                    </div>
                    <div className="flex-grow overflow-y-auto p-4 space-y-4">
                        {ticket.messages.map(msg => (
                            <div key={msg.id} className={`flex ${msg.sender === 'TENANT' ? 'justify-end' : 'justify-start'}`}>
                                <div className={`max-w-md p-3 rounded-lg ${msg.sender === 'TENANT' ? 'bg-cyan-900/50' : 'bg-slate-700'}`}>
                                    <p className="text-sm">{msg.message}</p>
                                    <p className="text-xs text-slate-500 text-right mt-1">{new Date(msg.timestamp).toLocaleString()}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                    {ticket.status !== 'Closed' && (
                        <div className="p-4 border-t border-slate-700 bg-slate-900/50">
                            <textarea value={replyMessage} onChange={e => setReplyMessage(e.target.value)} placeholder="Type your reply..." rows={3} className="w-full bg-slate-700 p-2 rounded-md border border-slate-600"/>
                            <div className="text-right mt-2">
                                <button onClick={handleReply} className="bg-cyan-600 hover:bg-cyan-500 text-white font-bold py-2 px-4 rounded-md">Send Reply</button>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        );
    };

    return (
        <div className="p-6 bg-slate-800 rounded-lg shadow-lg border border-slate-700">
            <div className="flex justify-between items-center mb-6">
                <h2 className="text-2xl font-bold text-white">Support Center</h2>
                <button onClick={() => setCreateModalOpen(true)} className="bg-cyan-600 hover:bg-cyan-500 text-white font-bold py-2 px-4 rounded-md flex items-center">
                    <Icon name="plus" className="w-5 h-5 mr-2" />
                    Create New Ticket
                </button>
            </div>
            <div className="overflow-x-auto">
                <table className="w-full text-left">
                    <thead className="border-b border-slate-700 text-xs text-slate-400 uppercase">
                        <tr>
                            <th className="p-3">Subject</th>
                            <th className="p-3 text-center">Status</th>
                            <th className="p-3">Last Updated</th>
                            <th className="p-3 text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {tenantTickets.map(ticket => (
                            <tr key={ticket.id} className="border-b border-slate-800 hover:bg-slate-700/50 text-sm">
                                <td className="p-3">{ticket.subject}</td>
                                <td className="p-3 text-center">{getStatusBadge(ticket.status)}</td>
                                <td className="p-3 whitespace-nowrap text-slate-400">{new Date(ticket.updatedAt).toLocaleString()}</td>
                                <td className="p-3 text-center">
                                    <button onClick={() => setSelectedTicket(ticket)} className="text-cyan-400 hover:text-cyan-300 font-semibold text-xs">View Details</button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
                {tenantTickets.length === 0 && <p className="text-center text-slate-500 py-12">You have not submitted any support tickets.</p>}
            </div>

            {isCreateModalOpen && <CreateTicketModal onClose={() => setCreateModalOpen(false)} />}
            {selectedTicket && <ViewTicketModal ticket={selectedTicket} onClose={() => setSelectedTicket(null)} />}
        </div>
    );
};

export default TenantSupport;